#!/bin/bash
#CODIGO PARA SUMAR RESTAR O MULTIPLICAR 2 NUMEROS INGRESADOS POR EL USUARIO
#lab 4
#HEISSEL GUSTAVO MENDEZ RAMIREZ 1674452
function suma(){
	sum=$(($a + $b))
	echo "el resultado es" $sum
}
function resta(){
	rest=$(($a - $b))
	echo "el resultado es" $rest
}
function multiplicacion(){
	mult=$(($a * $b))
	echo "el resultado es" $mult
}

function menu(){
	read -p "Ingresa el primer numero: " a
	read -p "Ingresa el segundo numero: " b
}

for i in 1
do
	menu
	echo "	||||Bienvenido al menu||||  "
	read -p "1 para sumar -- 2 para restar -- 3 para multiplicar  -- 4 salir" var
	
	case $var in
		1)suma
		  x=1
		  ;;
		2)resta
		  x=1
		  ;;
		3)multiplicacion
		  x=1
		  ;;
		4)echo "Gracias"
      echo "Saliendo..."
		  sleep 3
		  ;;
	esac
done
